# Custom Language File for Launcher Customizer

[ejs.app]
title = "Orizon Launcher"

[ejs.landing]
mediaGitHubURL = "https://orizonrp.fr/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/orizon"

[ejs.settings]
sourceGithubLink = "https://github.com/Nefers12/ouais"
supportLink = "https://github.com/Nefers12/ouais/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ORIZONRP"
welcomeDescription = "Notre mission est de recrÃ©er un univers shinobi militaire, inspirÃ© du monde de Naruto, oÃ¹ stratÃ©gie, discipline et intrigue se mÃªlent au roleplay le plus complet possible. DerriÃ¨re les uniformes impeccables et les ordres criÃ©s sur le terrain, câ€™est la communautÃ© dâ€™Orizon qui donne vie Ã  ce monde, une armÃ©e de passionnÃ©s, de rÃªveursâ€¦ et, oui, de quelques cornichons bien dressÃ©s."
welcomeDescCTA = "ApprÃªtez-vous Ã  sauter dans le bocal !ğŸ¥’"
